spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: ********************
      secret-key: ********************
      oss:
        bucket: ********************
        endpoint: ********************
  application:
    name: mall-third-party

server:
  port: 30000
